### ISSUE TITLE
Build for iOS

### ISSUE THREAD

**Issue by moreli** [liuliu/ccv#22]
Would you mind giving an example on how to build for iOS? Tried several options and it keeps failing. XCODE or thru terminal. Thanks!

**Comment by stevegraham** [comment]
+1

**Comment by liuliu** [comment]
I will try it again tomorrow. The last time I checked, you can drag-n-drop ccv to your Xcode project and compile, maybe I got some breakages after the dpm implementation.

**Comment by koudelka** [comment]
Throw this in your lib/.DEF file, using clang:

`-arch armv7 -miphoneos-version-min=5.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.1.sdk`

you'll also have to comment out the xmmintrin.h in ccv.h, too, since (afaik) the iphone doesn't have SSE.

You can then just link in the generated .a library.

Obviously not a complete solution, but it should get you started.

**Comment by liuliu** [comment]
Thanks, @koudelka SSE support is indeed the problem. Added directive to remove SSE support, this should be fixed in latest unstable/stable/r0.1-rc1 branch.

**Comment by moreli** [comment]
still fails 
fatal error: too many errors emitted, stopping now [-ferror-limit=]
8 warnings and 20 errors generated.
make: **\* [ccv_basic.o] Error 1

it complains about declared parameters
ccv_basic.c:226:2: error: use of undeclared identifier '__m128'
        __m128 eps = _mm_set1_ps((float)1e-6), absmask = ...
        ^
ccv_basic.c:227:2: error: use of undeclared identifier '__m128'
        __m128 _90 = _mm_set1_ps((float)(3.141592654 \* 0.5)), _180 = ...
        ^
ccv_basic.c:228:2: error: use of undeclared identifier '__m128'
        __m128 zero = _mm_setzero_ps(), _0_28 = _mm_set1_ps(0.28f), ...
        ^
ccv_basic.c:232:3: error: use of undeclared identifier '__m128'
                __m128 x4 = _mm_loadu_ps(x + i), y4 = _mm_loadu_ps(y + i);
                ^
ccv_basic.c:233:3: error: use of undeclared identifier '__m128'
                __m128 xq4 = _mm_mul_ps(x4, x4), yq4 = _mm_mul_ps(y4, y4);
                ^

**Comment by liuliu** [comment]
Try to use the latest stable, also, run ./configure force, and select no for all the questions (except the first one).

With the latest stable, you should be able to actually drop the code in and it will work (I've guarded against the SSE optimized code).

**Comment by moreli** [comment]
Thanks for the response. I've created a small script which worked in creating ios static library
for your reference...

``` script
#!/bin/sh
# build.sh

# eli mor (eli_mor.geo at yahoo) ccv (https://github.com/liuliu/ccv) ios build library
# http://tinsuke.wordpress.com/2011/11/01/how-to-compile-and-use-tesseract-3-01-on-ios-sdk-5/
# copy jpeg / png libs to ./usr/

GLOBAL_OUTDIR="`pwd`/compiled"
LOCAL_OUTDIR="./outdir"
INCLUDE_DIRECTORY="`pwd`/usr/include"
LIB_DIRECTORY="`pwd`/usr/lib"

IOS_BASE_SDK="5.1"
IOS_DEPLOY_TGT="4.3"

setenv_all()
{
    # Add internal libs
    export CFLAGS="$CFLAGS -D HAVE_LIBJPEG -I$INCLUDE_DIRECTORY"

    export CXX="$DEVROOT/usr/bin/llvm-g++"
    export CC="$DEVROOT/usr/bin/llvm-gcc"

    export LD=$DEVROOT/usr/bin/ld
    export AR=$DEVROOT/usr/bin/ar
    export AS=$DEVROOT/usr/bin/as
    export NM=$DEVROOT/usr/bin/nm
    export RANLIB=$DEVROOT/usr/bin/ranlib
    export LDFLAGS="-lm -ljpeg -L$SDKROOT/usr/lib/ -L$LIB_DIRECTORY"

    export CPPFLAGS=$CFLAGS
    export CXXFLAGS=$CFLAGS
}

setenv_arm6()
{
    unset DEVROOT SDKROOT CFLAGS CC LD CPP CXX AR AS NM CXXCPP RANLIB LDFLAGS CPPFLAGS CXXFLAGS

    export DEVROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer
    export SDKROOT=$DEVROOT/SDKs/iPhoneOS$IOS_BASE_SDK.sdk

    export CFLAGS="-arch armv6 -miphoneos-version-min=5.0 -isysroot $SDKROOT -I$SDKROOT/usr/include/"

    setenv_all
}

setenv_arm7()
{
    unset DEVROOT SDKROOT CFLAGS CC LD CPP CXX AR AS NM CXXCPP RANLIB LDFLAGS CPPFLAGS CXXFLAGS

    export DEVROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer
    export SDKROOT=$DEVROOT/SDKs/iPhoneOS$IOS_BASE_SDK.sdk

    export CFLAGS="-arch armv7 -miphoneos-version-min=5.0 -isysroot $SDKROOT -I$SDKROOT/usr/include/"

    setenv_all
}

setenv_i386()
{
    unset DEVROOT SDKROOT CFLAGS CC LD CPP CXX AR AS NM CXXCPP RANLIB LDFLAGS CPPFLAGS CXXFLAGS

    export DEVROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer
    export SDKROOT=$DEVROOT/SDKs/iPhoneSimulator$IOS_BASE_SDK.sdk

    export CFLAGS="-arch i386 -isysroot $SDKROOT -I$SDKROOT/usr/include/"

    setenv_all
}

create_outdir_lipo()
{
    for lib_i386 in `find $LOCAL_OUTDIR/i386 -name "lib*\.a"`; do
        lib_arm6=`echo $lib_i386 | sed "s/i386/arm6/g"`
        lib_arm7=`echo $lib_i386 | sed "s/i386/arm7/g"`
        lib=`echo $lib_i386 | sed "s/i386\///g"`
        lipo -arch armv6 $lib_arm6 -arch armv7 $lib_arm7 -arch i386 $lib_i386 -create -output $lib
    done
}

#######################
# CCV Lib
#######################
cd lib
rm -rf $LOCAL_OUTDIR
mkdir -p $LOCAL_OUTDIR/arm6 $LOCAL_OUTDIR/arm7 $LOCAL_OUTDIR/i386
echo "clang" > .CC

make clean 2> /dev/null
make distclean 2> /dev/null
setenv_arm6
echo $CFLAGS > .DEF
echo $LDFLAGS > .LN
make all
cp -rvf lib*.a $LOCAL_OUTDIR/arm6

make clean 2> /dev/null
make distclean 2> /dev/null
setenv_arm7
echo $CFLAGS > .DEF
echo $LDFLAGS > .LN
make all
cp -rvf lib*.a $LOCAL_OUTDIR/arm7

make clean 2> /dev/null
make distclean 2> /dev/null
setenv_i386
echo $CFLAGS > .DEF
echo $LDFLAGS > .LN
make all
cp -rvf lib*.a $LOCAL_OUTDIR/i386

create_outdir_lipo
mkdir -p $GLOBAL_OUTDIR/include && cp -rvf *.h $GLOBAL_OUTDIR/include
mkdir -p $GLOBAL_OUTDIR/lib && cp -rvf $LOCAL_OUTDIR/lib*.a $GLOBAL_OUTDIR/lib

echo "Finished!"
```
